// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbSxecPM8P-0qoU3eVi4RNy1COLdBG1c',
    appId: '1:917528612495:web:e7275f233b634fc8a2aafa',
    messagingSenderId: '917528612495',
    projectId: 'financeapp-39160',
    authDomain: 'financeapp-39160.firebaseapp.com',
    storageBucket: 'financeapp-39160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRjAvwF45VqKW_X6ylZLl_0s65LypYAcM',
    appId: '1:917528612495:android:bdc03c1279829246a2aafa',
    messagingSenderId: '917528612495',
    projectId: 'financeapp-39160',
    storageBucket: 'financeapp-39160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpgAyflWx1pKUy7GOQ3l6FMZ5G12o7Uk',
    appId: '1:917528612495:ios:6ba68e15f68f0dd9a2aafa',
    messagingSenderId: '917528612495',
    projectId: 'financeapp-39160',
    storageBucket: 'financeapp-39160.appspot.com',
    iosBundleId: 'com.example.financeTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpgAyflWx1pKUy7GOQ3l6FMZ5G12o7Uk',
    appId: '1:917528612495:ios:748a328637cda888a2aafa',
    messagingSenderId: '917528612495',
    projectId: 'financeapp-39160',
    storageBucket: 'financeapp-39160.appspot.com',
    iosBundleId: 'com.example.financeTrackApp.RunnerTests',
  );
}
